# Site settings
title: 星&花
header-img: "img/facebook.jpg"
tagline: "cn"  
description: "王青君|流离·幻影"  
baseurl: ""
url: "http://1loveyou.github.io"  

# About/contact
owner: 
  name: " 青君"
  email: ireneng@foxmail.com
  bio: "阅读使我在路上"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

douban_username:  cnfeat
twitter_username: feat
github_username: 1loveyou
facebook_username: 
weibo_username: iwangu 
zhihu_username: qing-jun-33

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems: 
- jekyll-gallery-generator
- jekyll-paginate
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Qing"
      header-img: "img/facebook.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : iwangwei
  disqus :
      short_name : iwangwei

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
